<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AdminView.aspx.cs" Inherits="AdminView" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    <br />
    <div class="container">

    <!-- ===== Feature 10: Triage Escalation Alert ===== -->
    <asp:Panel ID="PanelEscalation" runat="server" Visible="false">
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp;
        <asp:Label ID="LblEscalation" runat="server" />
      </div>
    </asp:Panel>

    <!-- ===== Feature 10: AI Dashboard Insights Panel ===== -->
    <div class="panel panel-info" style="margin-bottom:30px;">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-stats"></span>
          AI Dashboard Insights
          <asp:Button ID="BtnRefreshInsights" runat="server" Text="Refresh" CssClass="btn btn-xs btn-default pull-right"
                      OnClick="BtnRefreshInsights_Click" />
        </h3>
      </div>
      <div class="panel-body">
        <asp:Literal ID="LitInsights" runat="server" Text="Click Refresh to generate AI insights from current appointment data." />
      </div>
    </div>

    <!-- ===== Admins GridView ===== -->
    <h3>Administrators</h3>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" Height="191px" Width="758px">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="FirstName " HeaderText="FirstName " SortExpression="FirstName " />
            <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
            <asp:BoundField DataField="TypeOFUser" HeaderText="TypeOFUser" SortExpression="TypeOFUser" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
            <asp:BoundField DataField="Confirm" HeaderText="Confirm" SortExpression="Confirm" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>" SelectCommand="SELECT * FROM [Admins]"></asp:SqlDataSource>

    <!-- ===== Users GridView ===== -->
    <h3 style="margin-top:30px;">Registered Users</h3>
    <p>
        <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="MemberID" DataSourceID="SqlDataSource2">
            <Columns>
                <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowSelectButton="True" />
                <asp:BoundField DataField="MemberID" HeaderText="MemberID" InsertVisible="False" ReadOnly="True" SortExpression="MemberID" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="Month" HeaderText="Month" SortExpression="Month" />
                <asp:BoundField DataField="Day" HeaderText="Day" SortExpression="Day" />
                <asp:BoundField DataField="Year" HeaderText="Year" SortExpression="Year" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>" DeleteCommand="DELETE FROM [Users] WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL)) AND (([Month] = @original_Month) OR ([Month] IS NULL AND @original_Month IS NULL)) AND (([Day] = @original_Day) OR ([Day] IS NULL AND @original_Day IS NULL)) AND (([Year] = @original_Year) OR ([Year] IS NULL AND @original_Year IS NULL))" InsertCommand="INSERT INTO [Users] ([FirstName], [LastName], [Email], [Password], [Month], [Day], [Year]) VALUES (@FirstName, @LastName, @Email, @Password, @Month, @Day, @Year)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Users]" UpdateCommand="UPDATE [Users] SET [FirstName] = @FirstName, [LastName] = @LastName, [Email] = @Email, [Password] = @Password, [Month] = @Month, [Day] = @Day, [Year] = @Year WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL)) AND (([Month] = @original_Month) OR ([Month] IS NULL AND @original_Month IS NULL)) AND (([Day] = @original_Day) OR ([Day] IS NULL AND @original_Day IS NULL)) AND (([Year] = @original_Year) OR ([Year] IS NULL AND @original_Year IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_Password" Type="String" />
                <asp:Parameter Name="original_Month" Type="String" />
                <asp:Parameter Name="original_Day" Type="String" />
                <asp:Parameter Name="original_Year" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Month" Type="String" />
                <asp:Parameter Name="Day" Type="String" />
                <asp:Parameter Name="Year" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Month" Type="String" />
                <asp:Parameter Name="Day" Type="String" />
                <asp:Parameter Name="Year" Type="String" />
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_Password" Type="String" />
                <asp:Parameter Name="original_Month" Type="String" />
                <asp:Parameter Name="original_Day" Type="String" />
                <asp:Parameter Name="original_Year" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>

    <!-- ===== Feature 5: Contacts + Sentiment GridView ===== -->
    <h3 style="margin-top:30px;">Contact Enquiries <small style="color:#777;">AI Sentiment</small></h3>
    <p style="color:#555;">Sentiment badges are generated automatically by GPT-4 when patients submit a contact enquiry.</p>
        <asp:GridView ID="GridView4" runat="server" AllowPaging="True" AllowSorting="True"
            AutoGenerateColumns="False" DataKeyNames="MemberID" DataSourceID="SqlDataSource4"
            OnSelectedIndexChanged="GridView4_SelectedIndexChanged"
            OnRowDataBound="GridView4_RowDataBound"
            CssClass="table table-bordered table-hover" Width="100%">
            <Columns>
                <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowSelectButton="True" />
                <asp:BoundField DataField="MemberID"  HeaderText="ID"       InsertVisible="False" ReadOnly="True" SortExpression="MemberID" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName"  HeaderText="LastName"  SortExpression="LastName" />
                <asp:BoundField DataField="Email"     HeaderText="Email"     SortExpression="Email" />
                <asp:BoundField DataField="PhoneNum"  HeaderText="PhoneNum"  SortExpression="PhoneNum" />
                <asp:BoundField DataField="Message"   HeaderText="Message"   SortExpression="Message" />
                <asp:BoundField DataField="Sentiment" HeaderText="Sentiment" SortExpression="Sentiment" ItemStyle-Font-Bold="True" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConflictDetection="CompareAllValues"
            ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>"
            SelectCommand="SELECT MemberID, FirstName, LastName, Email, PhoneNum, Message, Sentiment FROM [Contacts]"
            DeleteCommand="DELETE FROM [Contacts] WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([PhoneNum] = @original_PhoneNum) OR ([PhoneNum] IS NULL AND @original_PhoneNum IS NULL)) AND (([Message] = @original_Message) OR ([Message] IS NULL AND @original_Message IS NULL))"
            InsertCommand="INSERT INTO [Contacts] ([FirstName], [LastName], [Email], [PhoneNum], [Message]) VALUES (@FirstName, @LastName, @Email, @PhoneNum, @Message)"
            OldValuesParameterFormatString="original_{0}"
            UpdateCommand="UPDATE [Contacts] SET [FirstName] = @FirstName, [LastName] = @LastName, [Email] = @Email, [PhoneNum] = @PhoneNum, [Message] = @Message WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([PhoneNum] = @original_PhoneNum) OR ([PhoneNum] IS NULL AND @original_PhoneNum IS NULL)) AND (([Message] = @original_Message) OR ([Message] IS NULL AND @original_Message IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_PhoneNum" Type="String" />
                <asp:Parameter Name="original_Message" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="PhoneNum" Type="String" />
                <asp:Parameter Name="Message" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="PhoneNum" Type="String" />
                <asp:Parameter Name="Message" Type="String" />
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_PhoneNum" Type="String" />
                <asp:Parameter Name="original_Message" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </p>

    <!-- ===== Appointments: triage + no-show risk + follow-up drafter ===== -->
    <h3 style="margin-top:30px;">
        Appointments
        <small style="color:#777;">AI Pre-Triage &amp; No-Show Risk</small>
    </h3>
    <p style="color:#555;">
        Triage levels and no-show risk ratings are generated automatically by GPT-4 at booking time.
    </p>

    <asp:GridView ID="GridView5" runat="server"
        AllowPaging="True" AllowSorting="True"
        AutoGenerateColumns="False"
        DataSourceID="SqlDataSource5"
        OnRowDataBound="GridView5_RowDataBound"
        CssClass="table table-bordered table-hover"
        Width="100%">
        <Columns>
            <asp:BoundField DataField="FirstName"  HeaderText="First Name"  SortExpression="FirstName" />
            <asp:BoundField DataField="Lastname"   HeaderText="Last Name"   SortExpression="Lastname" />
            <asp:BoundField DataField="Age"        HeaderText="Age"         SortExpression="Age" />
            <asp:BoundField DataField="Services"   HeaderText="Service"     SortExpression="Services" />
            <asp:BoundField DataField="PhoneNum"   HeaderText="Phone"       SortExpression="PhoneNum" />
            <asp:BoundField DataField="Issue"      HeaderText="Reason"      SortExpression="Issue" />
            <asp:BoundField DataField="AITriage"   HeaderText="AI Triage"   SortExpression="AITriage"  ItemStyle-Font-Bold="True" />
            <asp:BoundField DataField="AINote"     HeaderText="AI Pre-Assessment Note" />
            <asp:BoundField DataField="Time"       HeaderText="Time Slot"   SortExpression="Time" />
            <asp:BoundField DataField="NoShowRisk" HeaderText="No-Show Risk" SortExpression="NoShowRisk" ItemStyle-Font-Bold="True" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource5" runat="server"
        ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>"
        SelectCommand="SELECT FirstName, Lastname, Age, Services, PhoneNum, Issue, AITriage, AINote, Time, NoShowRisk FROM [Appointments]">
    </asp:SqlDataSource>

    <!-- ===== Feature 6: Follow-Up Email Drafter ===== -->
    <div class="panel panel-default" style="margin-top:20px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-envelope"></span>
          AI Follow-Up Email Drafter
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          Fill in the patient details below and click <strong>Generate</strong> to draft a
          personalised post-appointment follow-up email.
        </p>
        <div class="form-inline" style="margin-bottom:10px;">
          <label>Patient First Name:&nbsp;</label>
          <asp:TextBox ID="TxtFollowUpFirst"   runat="server" CssClass="form-control input-sm" placeholder="e.g. John" style="width:150px;" />
          &nbsp;
          <label>Service:&nbsp;</label>
          <asp:TextBox ID="TxtFollowUpService" runat="server" CssClass="form-control input-sm" placeholder="e.g. Cardiology" style="width:150px;" />
          &nbsp;
          <label>AI Note (optional):&nbsp;</label>
          <asp:TextBox ID="TxtFollowUpNote"    runat="server" CssClass="form-control input-sm" placeholder="AI pre-assessment text" style="width:200px;" />
          &nbsp;
          <asp:Button ID="BtnGenerateFollowUp" runat="server" Text="Generate" CssClass="btn btn-primary btn-sm"
                      OnClick="BtnGenerateFollowUp_Click" />
        </div>
        <asp:Panel ID="PanelFollowUp" runat="server" Visible="false">
          <div class="well well-sm" style="white-space:pre-wrap; font-family:monospace;">
            <asp:Literal ID="LitFollowUp" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== Feature 8: Doctor's Note Simplifier ===== -->
    <div class="panel panel-default" style="margin-top:20px; margin-bottom:40px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-edit"></span>
          Doctor's Note Simplifier
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          Paste a clinical note below. GPT-4 will rewrite it in plain, patient-friendly English.
        </p>
        <asp:TextBox ID="TxtClinicalNote" runat="server" TextMode="MultiLine"
                     Rows="5" CssClass="form-control" placeholder="Paste clinical / doctor's note here..." />
        <br />
        <asp:Button ID="BtnSimplifyNote" runat="server" Text="Simplify Note" CssClass="btn btn-warning btn-sm"
                    OnClick="BtnSimplifyNote_Click" />
        <asp:Panel ID="PanelSimplifiedNote" runat="server" Visible="false" style="margin-top:15px;">
          <div class="alert alert-info" style="white-space:pre-wrap;">
            <strong>Patient-Friendly Version:</strong><br />
            <asp:Literal ID="LitSimplifiedNote" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

 </div>

</asp:Content>
