<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AdminView.aspx.cs" Inherits="AdminView" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    <br />
    <div class="container">

    <!-- ===== Feature 10: Triage Escalation Alert ===== -->
    <asp:Panel ID="PanelEscalation" runat="server" Visible="false">
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp;
        <asp:Label ID="LblEscalation" runat="server" />
      </div>
    </asp:Panel>

    <!-- ===== Feature 10: AI Dashboard Insights Panel ===== -->
    <div class="panel panel-info" style="margin-bottom:30px;">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-stats"></span>
          AI Dashboard Insights
          <asp:Button ID="BtnRefreshInsights" runat="server" Text="Refresh" CssClass="btn btn-xs btn-default pull-right"
                      OnClick="BtnRefreshInsights_Click" />
        </h3>
      </div>
      <div class="panel-body">
        <asp:Literal ID="LitInsights" runat="server" Text="Click Refresh to generate AI insights from current appointment data." />
      </div>
    </div>

    <!-- ===== Admins GridView ===== -->
    <h3>Administrators</h3>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" Height="191px" Width="758px">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="FirstName " HeaderText="FirstName " SortExpression="FirstName " />
            <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
            <asp:BoundField DataField="TypeOFUser" HeaderText="TypeOFUser" SortExpression="TypeOFUser" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
            <asp:BoundField DataField="Confirm" HeaderText="Confirm" SortExpression="Confirm" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>" SelectCommand="SELECT * FROM [Admins]"></asp:SqlDataSource>

    <!-- ===== Users GridView ===== -->
    <h3 style="margin-top:30px;">Registered Users</h3>
    <p>
        <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="MemberID" DataSourceID="SqlDataSource2">
            <Columns>
                <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowSelectButton="True" />
                <asp:BoundField DataField="MemberID" HeaderText="MemberID" InsertVisible="False" ReadOnly="True" SortExpression="MemberID" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="Month" HeaderText="Month" SortExpression="Month" />
                <asp:BoundField DataField="Day" HeaderText="Day" SortExpression="Day" />
                <asp:BoundField DataField="Year" HeaderText="Year" SortExpression="Year" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>" DeleteCommand="DELETE FROM [Users] WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL)) AND (([Month] = @original_Month) OR ([Month] IS NULL AND @original_Month IS NULL)) AND (([Day] = @original_Day) OR ([Day] IS NULL AND @original_Day IS NULL)) AND (([Year] = @original_Year) OR ([Year] IS NULL AND @original_Year IS NULL))" InsertCommand="INSERT INTO [Users] ([FirstName], [LastName], [Email], [Password], [Month], [Day], [Year]) VALUES (@FirstName, @LastName, @Email, @Password, @Month, @Day, @Year)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Users]" UpdateCommand="UPDATE [Users] SET [FirstName] = @FirstName, [LastName] = @LastName, [Email] = @Email, [Password] = @Password, [Month] = @Month, [Day] = @Day, [Year] = @Year WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL)) AND (([Month] = @original_Month) OR ([Month] IS NULL AND @original_Month IS NULL)) AND (([Day] = @original_Day) OR ([Day] IS NULL AND @original_Day IS NULL)) AND (([Year] = @original_Year) OR ([Year] IS NULL AND @original_Year IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_Password" Type="String" />
                <asp:Parameter Name="original_Month" Type="String" />
                <asp:Parameter Name="original_Day" Type="String" />
                <asp:Parameter Name="original_Year" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Month" Type="String" />
                <asp:Parameter Name="Day" Type="String" />
                <asp:Parameter Name="Year" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Month" Type="String" />
                <asp:Parameter Name="Day" Type="String" />
                <asp:Parameter Name="Year" Type="String" />
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_Password" Type="String" />
                <asp:Parameter Name="original_Month" Type="String" />
                <asp:Parameter Name="original_Day" Type="String" />
                <asp:Parameter Name="original_Year" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>

    <!-- ===== Feature 5: Contacts + Sentiment GridView ===== -->
    <h3 style="margin-top:30px;">Contact Enquiries <small style="color:#777;">AI Sentiment</small></h3>
    <p style="color:#555;">Sentiment badges are generated automatically by GPT-4 when patients submit a contact enquiry.</p>
        <asp:GridView ID="GridView4" runat="server" AllowPaging="True" AllowSorting="True"
            AutoGenerateColumns="False" DataKeyNames="MemberID" DataSourceID="SqlDataSource4"
            OnSelectedIndexChanged="GridView4_SelectedIndexChanged"
            OnRowDataBound="GridView4_RowDataBound"
            CssClass="table table-bordered table-hover" Width="100%">
            <Columns>
                <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowSelectButton="True" />
                <asp:BoundField DataField="MemberID"  HeaderText="ID"       InsertVisible="False" ReadOnly="True" SortExpression="MemberID" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName"  HeaderText="LastName"  SortExpression="LastName" />
                <asp:BoundField DataField="Email"     HeaderText="Email"     SortExpression="Email" />
                <asp:BoundField DataField="PhoneNum"  HeaderText="PhoneNum"  SortExpression="PhoneNum" />
                <asp:BoundField DataField="Message"   HeaderText="Message"   SortExpression="Message" />
                <asp:BoundField DataField="Sentiment" HeaderText="Sentiment" SortExpression="Sentiment" ItemStyle-Font-Bold="True" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConflictDetection="CompareAllValues"
            ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>"
            SelectCommand="SELECT MemberID, FirstName, LastName, Email, PhoneNum, Message, Sentiment FROM [Contacts]"
            DeleteCommand="DELETE FROM [Contacts] WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([PhoneNum] = @original_PhoneNum) OR ([PhoneNum] IS NULL AND @original_PhoneNum IS NULL)) AND (([Message] = @original_Message) OR ([Message] IS NULL AND @original_Message IS NULL))"
            InsertCommand="INSERT INTO [Contacts] ([FirstName], [LastName], [Email], [PhoneNum], [Message]) VALUES (@FirstName, @LastName, @Email, @PhoneNum, @Message)"
            OldValuesParameterFormatString="original_{0}"
            UpdateCommand="UPDATE [Contacts] SET [FirstName] = @FirstName, [LastName] = @LastName, [Email] = @Email, [PhoneNum] = @PhoneNum, [Message] = @Message WHERE [MemberID] = @original_MemberID AND (([FirstName] = @original_FirstName) OR ([FirstName] IS NULL AND @original_FirstName IS NULL)) AND (([LastName] = @original_LastName) OR ([LastName] IS NULL AND @original_LastName IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([PhoneNum] = @original_PhoneNum) OR ([PhoneNum] IS NULL AND @original_PhoneNum IS NULL)) AND (([Message] = @original_Message) OR ([Message] IS NULL AND @original_Message IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_PhoneNum" Type="String" />
                <asp:Parameter Name="original_Message" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="PhoneNum" Type="String" />
                <asp:Parameter Name="Message" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="PhoneNum" Type="String" />
                <asp:Parameter Name="Message" Type="String" />
                <asp:Parameter Name="original_MemberID" Type="Int32" />
                <asp:Parameter Name="original_FirstName" Type="String" />
                <asp:Parameter Name="original_LastName" Type="String" />
                <asp:Parameter Name="original_Email" Type="String" />
                <asp:Parameter Name="original_PhoneNum" Type="String" />
                <asp:Parameter Name="original_Message" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </p>

    <!-- ===== Appointments: triage + no-show risk + follow-up drafter ===== -->
    <h3 style="margin-top:30px;">
        Appointments
        <small style="color:#777;">AI Pre-Triage &amp; No-Show Risk</small>
    </h3>
    <p style="color:#555;">
        Triage levels and no-show risk ratings are generated automatically by GPT-4 at booking time.
    </p>

    <asp:GridView ID="GridView5" runat="server"
        AllowPaging="True" AllowSorting="True"
        AutoGenerateColumns="False"
        DataSourceID="SqlDataSource5"
        OnRowDataBound="GridView5_RowDataBound"
        CssClass="table table-bordered table-hover"
        Width="100%">
        <Columns>
            <asp:BoundField DataField="FirstName"  HeaderText="First Name"  SortExpression="FirstName" />
            <asp:BoundField DataField="Lastname"   HeaderText="Last Name"   SortExpression="Lastname" />
            <asp:BoundField DataField="Age"        HeaderText="Age"         SortExpression="Age" />
            <asp:BoundField DataField="Services"   HeaderText="Service"     SortExpression="Services" />
            <asp:BoundField DataField="PhoneNum"   HeaderText="Phone"       SortExpression="PhoneNum" />
            <asp:BoundField DataField="Issue"      HeaderText="Reason"      SortExpression="Issue" />
            <asp:BoundField DataField="AITriage"   HeaderText="AI Triage"   SortExpression="AITriage"  ItemStyle-Font-Bold="True" />
            <asp:BoundField DataField="AINote"     HeaderText="AI Pre-Assessment Note" />
            <asp:BoundField DataField="Time"       HeaderText="Time Slot"   SortExpression="Time" />
            <asp:BoundField DataField="NoShowRisk" HeaderText="No-Show Risk" SortExpression="NoShowRisk" ItemStyle-Font-Bold="True" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource5" runat="server"
        ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>"
        SelectCommand="SELECT FirstName, Lastname, Age, Services, PhoneNum, Issue, AITriage, AINote, Time, NoShowRisk FROM [Appointments]">
    </asp:SqlDataSource>

    <!-- ===== Feature 6: Follow-Up Email Drafter ===== -->
    <div class="panel panel-default" style="margin-top:20px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-envelope"></span>
          AI Follow-Up Email Drafter
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          Fill in the patient details below and click <strong>Generate</strong> to draft a
          personalised post-appointment follow-up email.
        </p>
        <div class="form-inline" style="margin-bottom:10px;">
          <label>Patient First Name:&nbsp;</label>
          <asp:TextBox ID="TxtFollowUpFirst"   runat="server" CssClass="form-control input-sm" placeholder="e.g. John" style="width:150px;" />
          &nbsp;
          <label>Service:&nbsp;</label>
          <asp:TextBox ID="TxtFollowUpService" runat="server" CssClass="form-control input-sm" placeholder="e.g. Cardiology" style="width:150px;" />
          &nbsp;
          <label>AI Note (optional):&nbsp;</label>
          <asp:TextBox ID="TxtFollowUpNote"    runat="server" CssClass="form-control input-sm" placeholder="AI pre-assessment text" style="width:200px;" />
          &nbsp;
          <asp:Button ID="BtnGenerateFollowUp" runat="server" Text="Generate" CssClass="btn btn-primary btn-sm"
                      OnClick="BtnGenerateFollowUp_Click" />
        </div>
        <asp:Panel ID="PanelFollowUp" runat="server" Visible="false">
          <div class="well well-sm" style="white-space:pre-wrap; font-family:monospace;">
            <asp:Literal ID="LitFollowUp" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== Feature 8 (existing): Doctor's Note Simplifier ===== -->
    <div class="panel panel-default" style="margin-top:20px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-edit"></span>
          Doctor's Note Simplifier
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          Paste a clinical note below. GPT-4 will rewrite it in plain, patient-friendly English.
        </p>
        <asp:TextBox ID="TxtClinicalNote" runat="server" TextMode="MultiLine"
                     Rows="5" CssClass="form-control" placeholder="Paste clinical / doctor's note here..." />
        <br />
        <asp:Button ID="BtnSimplifyNote" runat="server" Text="Simplify Note" CssClass="btn btn-warning btn-sm"
                    OnClick="BtnSimplifyNote_Click" />
        <asp:Panel ID="PanelSimplifiedNote" runat="server" Visible="false" style="margin-top:15px;">
          <div class="alert alert-info" style="white-space:pre-wrap;">
            <strong>Patient-Friendly Version:</strong><br />
            <asp:Literal ID="LitSimplifiedNote" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== New Feature 6: Weekly Demand Forecast ===== -->
    <div class="panel panel-info" style="margin-top:20px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-calendar"></span>
          Weekly Demand Forecast
          <asp:Button ID="BtnForecast" runat="server" Text="Generate Forecast" CssClass="btn btn-xs btn-default pull-right"
                      OnClick="BtnForecast_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          GPT-4 analyses current booking data and predicts next week's demand by service to help plan staffing.
        </p>
        <asp:Panel ID="PanelForecast" runat="server" Visible="false">
          <div class="alert alert-info" style="white-space:pre-wrap;">
            <asp:Literal ID="LitForecast" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== New Feature 7: Referral Letter Drafter ===== -->
    <div class="panel panel-default" style="margin-top:20px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-file"></span>
          AI Referral Letter Drafter
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          Fill in the details below and GPT-4 will draft a formal inter-department referral letter.
        </p>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <label style="font-size:12px;">Patient Full Name</label>
              <asp:TextBox ID="TxtRefPatient" runat="server" CssClass="form-control input-sm" placeholder="e.g. John Smith" />
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <label style="font-size:12px;">Referring Doctor's Name</label>
              <asp:TextBox ID="TxtRefDoctor" runat="server" CssClass="form-control input-sm" placeholder="e.g. Dr. Adams" />
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <label style="font-size:12px;">From Department</label>
              <asp:DropDownList ID="DdlRefFrom" runat="server" CssClass="form-control input-sm">
                <asp:ListItem>General Practitioner</asp:ListItem>
                <asp:ListItem>Cardiology</asp:ListItem>
                <asp:ListItem>Gynaecology</asp:ListItem>
                <asp:ListItem>Opticology</asp:ListItem>
                <asp:ListItem>Paediatrics</asp:ListItem>
                <asp:ListItem>Radiology</asp:ListItem>
                <asp:ListItem>Surgery</asp:ListItem>
              </asp:DropDownList>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <label style="font-size:12px;">To Department</label>
              <asp:DropDownList ID="DdlRefTo" runat="server" CssClass="form-control input-sm">
                <asp:ListItem>Cardiology</asp:ListItem>
                <asp:ListItem>General Practitioner</asp:ListItem>
                <asp:ListItem>Gynaecology</asp:ListItem>
                <asp:ListItem>Opticology</asp:ListItem>
                <asp:ListItem>Paediatrics</asp:ListItem>
                <asp:ListItem>Radiology</asp:ListItem>
                <asp:ListItem>Surgery</asp:ListItem>
              </asp:DropDownList>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="form-group">
              <label style="font-size:12px;">Reason for Referral</label>
              <asp:TextBox ID="TxtRefReason" runat="server" TextMode="MultiLine" Rows="2"
                           CssClass="form-control input-sm" placeholder="Brief clinical reason for referral..." />
            </div>
          </div>
        </div>
        <asp:Button ID="BtnReferralLetter" runat="server" Text="Draft Letter" CssClass="btn btn-primary btn-sm"
                    OnClick="BtnReferralLetter_Click" />
        <asp:Panel ID="PanelReferralLetter" runat="server" Visible="false" style="margin-top:15px;">
          <div class="well well-sm" style="white-space:pre-wrap; font-family:monospace; font-size:13px;">
            <asp:Literal ID="LitReferralLetter" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== New Feature 8b: Complaint Escalation Handler ===== -->
    <div class="panel panel-danger" style="margin-top:20px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-warning-sign"></span>
          Complaint Escalation Handler
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          Paste a distressed patient message below and GPT-4 will draft a formal, empathetic complaint response.
        </p>
        <div class="form-inline" style="margin-bottom:10px;">
          <label>Patient First Name:&nbsp;</label>
          <asp:TextBox ID="TxtComplaintFirst" runat="server" CssClass="form-control input-sm"
                       placeholder="e.g. Mary" style="width:140px;" />
        </div>
        <asp:TextBox ID="TxtComplaint" runat="server" TextMode="MultiLine" Rows="4"
                     CssClass="form-control" placeholder="Paste the patient's complaint or distressed message here..." />
        <br />
        <asp:Button ID="BtnComplaintResponse" runat="server" Text="Draft Complaint Response"
                    CssClass="btn btn-danger btn-sm" OnClick="BtnComplaintResponse_Click" />
        <asp:Panel ID="PanelComplaintResponse" runat="server" Visible="false" style="margin-top:15px;">
          <div class="well well-sm" style="white-space:pre-wrap; font-family:monospace; font-size:13px;">
            <asp:Literal ID="LitComplaintResponse" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== New Feature 10: Monthly Health Newsletter Generator ===== -->
    <div class="panel panel-success" style="margin-top:20px; margin-bottom:30px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-send"></span>
          Monthly Health Newsletter Generator
          <asp:Button ID="BtnNewsletter" runat="server" Text="Generate Newsletter" CssClass="btn btn-xs btn-default pull-right"
                      OnClick="BtnNewsletter_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          GPT-4 reads this month's top services from the database and generates a ready-to-send patient newsletter.
        </p>
        <asp:Panel ID="PanelNewsletter" runat="server" Visible="false">
          <div class="well" style="white-space:pre-wrap; font-size:14px; line-height:1.7;">
            <asp:Literal ID="LitNewsletter" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== Patient Feedback Grid + AI Summary ===== -->
    <h3 style="margin-top:30px;">
        Patient Feedback
        <small style="color:#777;">Post-Appointment Ratings &amp; Sentiment</small>
    </h3>
    <p style="color:#555;">
        Ratings and sentiment badges are generated automatically by GPT-4 when patients submit feedback.
    </p>
    <asp:GridView ID="GridViewFeedback" runat="server"
        AllowPaging="True" AllowSorting="True"
        AutoGenerateColumns="False"
        DataSourceID="SqlDataSourceFeedback"
        OnRowDataBound="GridViewFeedback_RowDataBound"
        CssClass="table table-bordered table-hover" Width="100%">
        <Columns>
            <asp:BoundField DataField="Id"          HeaderText="ID"       InsertVisible="False" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="PatientName" HeaderText="Patient"  SortExpression="PatientName" />
            <asp:BoundField DataField="Service"     HeaderText="Service"  SortExpression="Service" />
            <asp:BoundField DataField="Rating"      HeaderText="Rating"   SortExpression="Rating" ItemStyle-Font-Bold="True" />
            <asp:BoundField DataField="Comment"     HeaderText="Comment"  SortExpression="Comment" />
            <asp:BoundField DataField="Sentiment"   HeaderText="Sentiment" SortExpression="Sentiment" ItemStyle-Font-Bold="True" />
            <asp:BoundField DataField="SubmittedAt" HeaderText="Submitted" SortExpression="SubmittedAt" DataFormatString="{0:dd MMM yyyy}" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSourceFeedback" runat="server"
        ConnectionString="<%$ ConnectionStrings:SignUpDBConnectionString1 %>"
        SelectCommand="SELECT Id, PatientName, Service, Rating, Comment, Sentiment, SubmittedAt FROM [Feedback] ORDER BY SubmittedAt DESC">
    </asp:SqlDataSource>

    <!-- AI Feedback Summary panel -->
    <div class="panel panel-warning" style="margin-top:20px;">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-stats"></span>
          AI Feedback Summary
          <asp:Button ID="BtnFeedbackSummary" runat="server" Text="Generate Summary"
              CssClass="btn btn-xs btn-default pull-right" OnClick="BtnFeedbackSummary_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">
          GPT-4 analyses all patient feedback and produces an executive summary of satisfaction trends,
          recurring themes, and recommended actions for management.
        </p>
        <asp:Panel ID="PanelFeedbackSummary" runat="server" Visible="false">
          <div class="alert alert-warning" style="white-space:pre-wrap;">
            <asp:Literal ID="LitFeedbackSummary" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- Quick link to Staff Bio Generator -->
    <div class="alert alert-info" style="margin-bottom:30px;">
      <span class="glyphicon glyphicon-user"></span>
      &nbsp;<strong>Staff Bio Generator:</strong>
      Create polished doctor biographies for the website.
      <a href="StaffBioGenerator.aspx" class="btn btn-info btn-sm pull-right">Open Bio Generator</a>
    </div>

    <!-- ===== Staff Performance Report ===== -->
    <div class="panel panel-default" style="margin-top:10px;">
      <div class="panel-heading">
        <h4 class="panel-title"><span class="glyphicon glyphicon-signal"></span> Staff Performance Report
          <asp:Button ID="BtnPerformanceReport" runat="server" Text="Generate Report"
              CssClass="btn btn-xs btn-primary pull-right" OnClick="BtnPerformanceReport_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">Cross-references appointment volumes, triage levels, no-show rates, and patient feedback to produce a management performance report.</p>
        <asp:Panel ID="PanelPerformanceReport" runat="server" Visible="false">
          <div class="alert alert-default" style="background:#f9f9f9;border:1px solid #ddd;white-space:pre-wrap;">
            <asp:Literal ID="LitPerformanceReport" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== Clinical Audit Report ===== -->
    <div class="panel panel-info" style="margin-top:10px;">
      <div class="panel-heading">
        <h4 class="panel-title"><span class="glyphicon glyphicon-folder-open"></span> Clinical Audit Report
          <asp:Button ID="BtnAuditReport" runat="server" Text="Generate Audit"
              CssClass="btn btn-xs btn-default pull-right" OnClick="BtnAuditReport_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">Formal clinical governance report covering triage distribution, no-show rates, complaint themes, and feedback trends with recommendations.</p>
        <asp:Panel ID="PanelAuditReport" runat="server" Visible="false">
          <div class="alert alert-info" style="white-space:pre-wrap;">
            <asp:Literal ID="LitAuditReport" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== Staff Training Topic Recommender ===== -->
    <div class="panel panel-warning" style="margin-top:10px;">
      <div class="panel-heading">
        <h4 class="panel-title"><span class="glyphicon glyphicon-education"></span> Staff Training Topic Recommender
          <asp:Button ID="BtnTraining" runat="server" Text="Get Recommendations"
              CssClass="btn btn-xs btn-default pull-right" OnClick="BtnTraining_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <p class="text-muted" style="font-size:13px;">Analyses complaint and feedback themes to recommend the top 5 staff training priorities, each with a suggested format.</p>
        <asp:Panel ID="PanelTraining" runat="server" Visible="false">
          <div class="alert alert-warning" style="white-space:pre-wrap;">
            <asp:Literal ID="LitTraining" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== Social Media Post Generator ===== -->
    <div class="panel panel-success" style="margin-top:10px;">
      <div class="panel-heading">
        <h4 class="panel-title"><span class="glyphicon glyphicon-share"></span> Social Media Post Generator
          <asp:Button ID="BtnSocialPost" runat="server" Text="Generate Post"
              CssClass="btn btn-xs btn-default pull-right" OnClick="BtnSocialPost_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-5">
            <div class="form-group">
              <label style="font-size:13px;">Topic / Health Awareness Theme</label>
              <asp:TextBox ID="TxtSocialTopic" runat="server" CssClass="form-control input-sm"
                  placeholder="e.g. World Heart Day, diabetes awareness, staying active..." />
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <label style="font-size:13px;">Platform</label>
              <asp:DropDownList ID="DdlSocialPlatform" runat="server" CssClass="form-control input-sm">
                <asp:ListItem>Facebook</asp:ListItem>
                <asp:ListItem>Instagram</asp:ListItem>
                <asp:ListItem>Twitter / X</asp:ListItem>
                <asp:ListItem>LinkedIn</asp:ListItem>
              </asp:DropDownList>
            </div>
          </div>
        </div>
        <asp:Panel ID="PanelSocialPost" runat="server" Visible="false">
          <div class="alert alert-success" style="white-space:pre-wrap;">
            <asp:Literal ID="LitSocialPost" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

    <!-- ===== Meeting Agenda Generator ===== -->
    <div class="panel panel-default" style="margin-top:10px;margin-bottom:40px;">
      <div class="panel-heading">
        <h4 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span> Meeting Agenda Generator
          <asp:Button ID="BtnAgenda" runat="server" Text="Generate Agenda"
              CssClass="btn btn-xs btn-primary pull-right" OnClick="BtnAgenda_Click" />
        </h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label style="font-size:13px;">Meeting Title</label>
              <asp:TextBox ID="TxtMeetingTitle" runat="server" CssClass="form-control input-sm"
                  placeholder="e.g. Monthly Clinical Governance Meeting" />
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <label style="font-size:13px;">Attendees</label>
              <asp:TextBox ID="TxtMeetingAttendees" runat="server" CssClass="form-control input-sm"
                  placeholder="e.g. Dr. Smith, Head Nurse, Admin Manager..." />
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <label style="font-size:13px;">Meeting Date</label>
              <asp:TextBox ID="TxtMeetingDate" runat="server" CssClass="form-control input-sm"
                  placeholder="e.g. 10 March 2026" />
            </div>
          </div>
        </div>
        <div class="form-group">
          <label style="font-size:13px;">Discussion Topics (one per line)</label>
          <asp:TextBox ID="TxtMeetingTopics" runat="server" TextMode="MultiLine" Rows="3"
              CssClass="form-control input-sm"
              placeholder="e.g. Review of triage escalation data&#10;Patient feedback analysis&#10;Staffing rota for next month" />
        </div>
        <asp:Panel ID="PanelAgenda" runat="server" Visible="false">
          <div class="alert alert-default" style="background:#f9f9f9;border:1px solid #ddd;white-space:pre-wrap;">
            <asp:Literal ID="LitAgenda" runat="server" />
          </div>
        </asp:Panel>
      </div>
    </div>

 </div>

</asp:Content>
