<%@ Page Title="Allergy & Food Safety Guide" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AllergyFoodGuide.aspx.cs" Inherits="AllergyFoodGuide" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div class="container" style="max-width:760px;margin-top:30px;margin-bottom:40px;">

  <h2><span class="glyphicon glyphicon-apple"></span> AI Allergy &amp; Food Safety Guide</h2>
  <p class="text-muted">
    Enter your known allergies and GPT-4 will generate a personalised food safety guide including
    foods to avoid, safe swaps, label-reading tips, and eating-out advice.
  </p>

  <div class="alert alert-warning">
    <span class="glyphicon glyphicon-warning-sign"></span>
    <strong>Important:</strong> This guide is for general educational purposes only and does not replace
    advice from your doctor, allergist, or dietitian. Always carry prescribed emergency medication such
    as an EpiPen if instructed by your doctor.
  </div>

  <div class="panel panel-default">
    <div class="panel-body">
      <div class="form-group">
        <label for="TxtAllergies">Your Known Allergies</label>
        <asp:TextBox ID="TxtAllergies" runat="server" CssClass="form-control"
            placeholder="e.g. peanuts, tree nuts, shellfish, dairy, gluten..." />
        <p class="help-block">Enter your allergies separated by commas.</p>
      </div>

      <asp:Label ID="LblError" runat="server" CssClass="text-danger" Visible="false" />

      <asp:Button ID="BtnGenerate" runat="server" Text="Generate My Food Safety Guide"
          CssClass="btn btn-warning" OnClick="BtnGenerate_Click" />
    </div>
  </div>

  <!-- Result panel -->
  <asp:Panel ID="PanelResult" runat="server" Visible="false">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="panel-title">
          <span class="glyphicon glyphicon-list-alt"></span>
          Your Personalised Food Safety Guide
          <button type="button" class="btn btn-xs btn-default pull-right" onclick="window.print()">
            <span class="glyphicon glyphicon-print"></span> Print
          </button>
        </h4>
      </div>
      <div class="panel-body" style="white-space:pre-wrap;font-size:14px;">
        <asp:Literal ID="LitGuide" runat="server" />
      </div>
    </div>
    <p class="text-muted" style="font-size:12px;">
      <span class="glyphicon glyphicon-info-sign"></span>
      Generated by GPT-4 based on the allergies you provided. Always verify with your healthcare provider.
    </p>
  </asp:Panel>

</div>
</asp:Content>
